import React, { useState } from 'react';
import { Calculator, ArrowRight, Sparkles, Check, TrendingUp, ShieldCheck } from 'lucide-react';
import { VipCrestEmblem } from './BrandIcons';
import { ParallaxHorizontalWrapper } from './ParallaxHorizontalWrapper';

interface BrandEquityCalculatorProps {
  onSelectPlanWithMetrics: (data: {
    sector: string;
    scale: string;
    multiplier: string;
  }) => void;
}

export const BrandEquityCalculator: React.FC<BrandEquityCalculatorProps> = ({
  onSelectPlanWithMetrics,
}) => {
  const [industry, setIndustry] = useState<'finance' | 'tech' | 'realestate' | 'advisory'>('finance');
  const [revenueScale, setRevenueScale] = useState<'tier1' | 'tier2' | 'tier3'>('tier2');

  const industryMultipliers = {
    finance: { label: 'Private Equity / Venture Capital / M&A', baseMultiplier: 4.2, dealFlowBoost: '+$45M – $120M' },
    tech: { label: 'Tech Founders & SaaS Scaleups', baseMultiplier: 3.8, dealFlowBoost: '+$25M – $80M' },
    realestate: { label: 'Ultra-Luxury Real Estate & Development', baseMultiplier: 3.5, dealFlowBoost: '+$30M – $95M' },
    advisory: { label: 'Global Strategy & Executive Advisory', baseMultiplier: 4.5, dealFlowBoost: '+$15M – $50M' },
  };

  const scaleImpact = {
    tier1: { label: '$5M – $25M Annual Gross', multiplierMod: 1.0, timeCompression: '60% faster deal closing' },
    tier2: { label: '$25M – $100M Enterprise Scale', multiplierMod: 1.25, timeCompression: '75% faster negotiation cycles' },
    tier3: { label: '$100M+ Sovereign / Institutional Scale', multiplierMod: 1.5, timeCompression: 'Immediate fiduciary pre-approval' },
  };

  const activeInd = industryMultipliers[industry];
  const activeScale = scaleImpact[revenueScale];
  const calculatedMultiplier = (activeInd.baseMultiplier * activeScale.multiplierMod).toFixed(1);

  return (
    <section id="calculator" className="relative py-28 px-6 sm:px-8 bg-[#0E0E0E] overflow-hidden border-t border-[#DDA83B]/15">
      <div className="max-w-7xl mx-auto relative z-10">
        
        {/* Asymmetric Header */}
        <ParallaxHorizontalWrapper direction="left" distance={60}>
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-end mb-16 pb-8 border-b border-white/10">
            <div className="lg:col-span-8">
              <span className="font-brand-sans text-xs uppercase tracking-[0.25em] text-[#DDA83B] font-semibold block mb-2">
                INTERACTIVE ROI ESTIMATOR
              </span>
              <h2 className="font-serif-luxury text-3xl sm:text-5xl font-bold tracking-tight text-white">
                BRAND EQUITY &amp; <span className="gold-gradient-text">DEAL MULTIPLIER</span>
              </h2>
            </div>
            <div className="lg:col-span-4 lg:text-right">
              <p className="font-body text-xs sm:text-sm text-[#FDFBF7]/75 leading-relaxed font-light">
                Estimate the economic premium and deal compression generated by sovereign executive authority.
              </p>
            </div>
          </div>
        </ParallaxHorizontalWrapper>

        {/* 2-Column Calculator Interface */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-stretch">
          {/* Left Column: Inputs */}
          <div className="lg:col-span-7 p-8 rounded-sm bg-[#141414] border border-[#DDA83B]/20 flex flex-col justify-between">
            <div className="space-y-8">
              {/* Step 1: Industry */}
              <div>
                <label className="font-brand-sans text-xs uppercase tracking-wider text-[#DDA83B] font-bold block mb-3">
                  1. Select Your Primary Industry Sector:
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {(Object.keys(industryMultipliers) as (keyof typeof industryMultipliers)[]).map(
                    (key) => {
                      const item = industryMultipliers[key];
                      const isSelected = industry === key;
                      return (
                        <button
                          key={key}
                          onClick={() => setIndustry(key)}
                          className={`p-3.5 rounded-sm border text-left font-brand-sans text-xs transition-all cursor-pointer flex items-center justify-between ${
                            isSelected
                              ? 'bg-[#1E1C18] border-[#DDA83B] text-white font-semibold shadow-md'
                              : 'bg-[#0E0E0E] border-[#1E1E1E] text-[#FDFBF7]/70 hover:border-[#DDA83B]/40 hover:text-white'
                          }`}
                        >
                          <span className="truncate pr-2">{item.label}</span>
                          {isSelected && <Check className="w-4 h-4 text-[#DDA83B] shrink-0" />}
                        </button>
                      );
                    }
                  )}
                </div>
              </div>

              {/* Step 2: Revenue Scale */}
              <div>
                <label className="font-brand-sans text-xs uppercase tracking-wider text-[#DDA83B] font-bold block mb-3">
                  2. Managed Capital / Company Revenue Scale:
                </label>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                  {(Object.keys(scaleImpact) as (keyof typeof scaleImpact)[]).map((key) => {
                    const item = scaleImpact[key];
                    const isSelected = revenueScale === key;
                    return (
                      <button
                        key={key}
                        onClick={() => setRevenueScale(key)}
                        className={`p-3.5 rounded-sm border text-left font-brand-sans text-xs transition-all cursor-pointer flex flex-col justify-between ${
                          isSelected
                            ? 'bg-[#1E1C18] border-[#DDA83B] text-white font-semibold shadow-md'
                            : 'bg-[#0E0E0E] border-[#1E1E1E] text-[#FDFBF7]/70 hover:border-[#DDA83B]/40 hover:text-white'
                        }`}
                      >
                        <span>{item.label}</span>
                        {isSelected && (
                          <Check className="w-3.5 h-3.5 text-[#DDA83B] shrink-0 mt-2" />
                        )}
                      </button>
                    );
                  })}
                </div>
              </div>
            </div>

            <div className="pt-6 mt-6 border-t border-[#1E1E1E] flex items-center gap-2 text-xs font-brand-sans text-[#FDFBF7]/50">
              <ShieldCheck className="w-4 h-4 text-[#DDA83B]" />
              <span>Calibrated against 100+ executive branding case studies</span>
            </div>
          </div>

          {/* Right Column: Dynamic Calculation Output */}
          <div className="lg:col-span-5 p-8 rounded-sm bg-gradient-to-b from-[#1A1814] to-[#0F0E0D] border-2 border-[#DDA83B]/40 flex flex-col justify-between shadow-2xl">
            <div>
              <div className="flex items-center justify-between mb-6 pb-4 border-b border-[#DDA83B]/20">
                <div className="flex items-center gap-2">
                  <TrendingUp className="w-4 h-4 text-[#DDA83B]" />
                  <span className="font-brand-sans text-xs uppercase tracking-widest text-[#DDA83B] font-bold">
                    ESTIMATED AUTHORITY MULTIPLIER
                  </span>
                </div>
                <VipCrestEmblem size={24} className="w-6 h-6 text-[#DDA83B]" />
              </div>

              <div className="text-center my-6">
                <span className="font-brand-sans text-xs uppercase tracking-widest text-[#FDFBF7]/60 block mb-1">
                  Estimated Brand Leverage Multiple:
                </span>
                <span className="font-serif-luxury text-6xl sm:text-7xl font-bold text-gold-metallic tabular-nums block">
                  {calculatedMultiplier}x
                </span>
                <span className="font-brand-sans text-xs text-[#DDA83B] font-semibold mt-1 block">
                  Projected Premium on Negotiations &amp; Deals
                </span>
              </div>

              <div className="space-y-3 p-4 rounded-sm bg-[#0A0A0A] border border-[#DDA83B]/20 mb-6 text-xs font-brand-sans">
                <div className="flex justify-between items-center">
                  <span className="text-[#FDFBF7]/60">Estimated Deal Flow Impact:</span>
                  <span className="text-white font-bold">{activeInd.dealFlowBoost}</span>
                </div>
                <div className="flex justify-between items-center">
                  <span className="text-[#FDFBF7]/60">Negotiation Velocity:</span>
                  <span className="text-[#DDA83B] font-semibold">{activeScale.timeCompression}</span>
                </div>
              </div>
            </div>

            <button
              onClick={() =>
                onSelectPlanWithMetrics({
                  sector: activeInd.label,
                  scale: activeScale.label,
                  multiplier: calculatedMultiplier,
                })
              }
              className="w-full py-4 px-6 rounded-sm font-brand-sans font-bold text-xs uppercase tracking-[0.2em] text-[#0B0B0B] bg-gold-gradient bg-gold-gradient-hover gold-glow transition-all duration-300 hover:scale-[1.02] cursor-pointer shadow-lg flex items-center justify-center gap-2"
            >
              <span>Apply With These Metrics</span>
              <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      </div>
    </section>
  );
};
